### ISSUE TITLE
Production live api stopt updating/working

### ISSUE THREAD

**Issue by jobvk** [damonnk/windcentrale#1]
### This list of API's stopt updating or working:

- [https://zep-api.windcentrale.nl/production/21/live](https://zep-api.windcentrale.nl/production/21/live) (stopt working, no values are returned)
- [https://zep-api.windcentrale.nl/production/31/live](https://zep-api.windcentrale.nl/production/31/live) (stopt updating on 2020-08-28 08:35:40)
- [https://zep-api.windcentrale.nl/production/41/live](https://zep-api.windcentrale.nl/production/41/live) (stopt updating on 2020-08-28 08:35:40)
- [https://zep-api.windcentrale.nl/production/51/live](https://zep-api.windcentrale.nl/production/51/live) (stopt updating on 2020-08-28 08:35:40)

**Comment by SimpelMind** [comment]
### News message from windcentrale.nl:

Dinsdag 1 september 2020 - Storing met de live verbinding windmolens in Culemborg

Het live volgen van de windmolens Rode Hert, Witte Juffer en Ranke Zwaan is tijdelijk niet mogelijk doordat er een storing is met de live verbinding. De weergegeven productie van de live api wordt momenteel niet bijgewerkt. De productiedata API is wel beschikbaar. Wij zoeken uit wat de reden is dat wij geen live verbinding hebben met de windmolens. Zodra wij hier meer over weten plaatsen wij een update.

Voor meer info zie [www.windcentrale.nl](www.windcentrale.nl)

**Comment by damonnk** [comment]
Hi @SimpelMind , Bedankt voor de  informatie. ik zal het in de gaten houden. Volgens de Windcentrale app is er inderdaad een storing. Dus helaas even geduld hebben.
